bind-address: 127.0.0.1:25580
proxy_threads: 4
prometheus:
  enabled: false
  listen-address: 127.0.0.1:19100
debug: true
redirections:
  - incoming_domain: localhost
    target: 127.0.0.1:25581
  - incoming_domain: 127.0.0.1
    target: 127.0.0.1:25581
