name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain (stable)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true

      - name: Build for x86_64
        run: |
          cargo build --release --target x86_64-unknown-linux-gnu
          ls -la target/x86_64-unknown-linux-gnu/release

      - name: Create GitHub Release (x86_64)
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-${{ github.run_number }}
          release_name: "Automated Build #${{ github.run_number }}"
          draft: false
          prerelease: false
          files: |
            # Replace 'myproject' with the *actual* filename from your ls step:
            target/x86_64-unknown-linux-gnu/release/myproject#myproject-x86_64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
