name: Build and Artifact

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true

      - name: Build for x86_64
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          ls -la target/x86_64-unknown-linux-musl/release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-binary
          path: target/x86_64-unknown-linux-musl/release/mineshieldv2-proxy
