name: Build and Artifact
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC_x86_64_unknown_linux_musl: musl-gcc
      AR_x86_64_unknown_linux_musl: ar
      CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER: musl-gcc
      LIBSQLITE3_SYS_BUNDLED: "1"   # build SQLite from source for MUSL
      PKG_CONFIG_ALLOW_CROSS: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-unknown-linux-musl

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install MUSL toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y musl-tools pkg-config

      - name: Build
        run: cargo build

      - name: Unit tests
        run: cargo test

      - name: Build (musl, static)
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          ls -la target/x86_64-unknown-linux-musl/release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: mineshield-proxy-x86_64-musl
          path: target/x86_64-unknown-linux-musl/release/mineshieldv2-proxy
