name: Build and Release

on:
  push:
    branches: [ main ]
    
jobs:
  release:
    name: Build and Release for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-pc-windows-gnu, x86_64-unknown-linux-musl ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # Generate a unique tag for each push (avoids "already_exists" error)
          tag_name: build-${{ github.run_number }}-${{ github.run_id }}
          release_name: "Release build #${{ github.run_number }}"
          draft: false
          prerelease: false

      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
