name: Build and Artifact

on:
  push:
    branches: [ main ]
    
jobs:
  build:
    name: Build for ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ x86_64-unknown-linux-musl ]
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Compile and upload artifact
        uses: rust-build/rust-build.action@v1.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          EXTRA_FILES: "README.md LICENSE"
          UPLOAD_MODE: artifact
